-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
/*--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------*/
TEAM_AOD = DarkRP.createJob("Staff on Duty", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/combine_super_soldier.mdl"},
   description = [[YOU ARE AN ADMIN ON DUTY! DO NOT ROLEPLAY! DO NOT ABUSE!]],
   weapons = {},
   command = "aod",
   max = 0,
   salary = 0,
   admin = 1,
   vote = false,
   hasLicense = false,
   candemote = false,
   category = "Administration",
})

TEAM_SCAVENGER = AddExtraTeam("Scavenger", {
	level = 1,
	color = Color(20, 150, 20, 255),
    model = "models/player/arctic.mdl",
    description = [[Go out and scavenge through the Cilians bases and take their stuff.]],
    weapons = {"weapon_fists", "lockpick", "keypad_cracker"},
    command = "scavenger",
    max = 5,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

TEAM_GUN = AddExtraTeam("Weapons Dealer", {
    level = 1,
    color = Color(20, 150, 20, 255),
    model = "models/player/pmc_3/pmc__01.mdl",
    description = [[Neautral party to all wars. Supply weapons to soldiers.]],
    weapons = {},
    command = "dealer",
    max = 3,
    salary = 45,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Civilians"
})

// UNITED STATES //

TEAM_US1 = DarkRP.createJob("US Infantry", {
	level = 1,
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2h.mdl"},
   description = [[You are an infantry unit for the United States Army. Follow your superior's orders and lead the U.S to victory!]],
   weapons = {"cw_g4p_m4a1", "cw_g4p_glock17"},
   command = "usinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "United States",
})

TEAM_US2 = DarkRP.createJob("US Recon Unit", {
	level = 1,
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_2/pmc__03.mdl"},
   description = [[You are a recon unit for the United States Army. Your job is to gather intel on enemy units]],
   weapons = {"util_binoculars", "cw_g4p_glock17"},
   command = "usrecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
   PlayerCanPickupWeapon = function(ply, weapon) return true end
})

TEAM_US3 = DarkRP.createJob("US Heavy Infantry", {
	level = 20,
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2.mdl"},
   description = [[You are a heavy infantry unit for the United States Army. You are up close and personal and would be the first to enter a base while raiding.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "usheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US4 = DarkRP.createJob("US Sniper", {
	level = 30,
   color = Color(0, 128, 255, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for the United States Army. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"cw_g4p_m98b", "cw_g4p_glock17"},
   command = "ussniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US5 = DarkRP.createJob("US Light Machine Gunner", {
	level = 50,
   color = Color(0, 128, 255, 255),
   level = 15,
   model = {"models/codmw2/codmw2.mdl"},
   description = [[You are a light machine gunner for the United States Army. Your job is to defend your base. YOU ARE NOT TO JOIN RAIDS. YOU ARE A DEFENSIVE UNIT, NOT AN OFFENSIVE UNIT!]],
   weapons = {"cw_240b", "cw_g4p_glock17"},
   command = "uslightmachinegunner",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US6 = DarkRP.createJob("US Medic", {
	level = 15,
   color = Color(0, 128, 255, 255),
   model = {"models/mw2guy/bz/tfbz02.mdl"},
   description = [[You are a medic for the United States Army. You're job is to heal your team and keep them alive!]],
   weapons = {"weapon_medkit", "cw_g4p_ump45", "cw_g4p_glock17"},
   command = "usmedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US7 = DarkRP.createJob("US Lieutenant", {
	level = 50,
   color = Color(0, 128, 255, 255),
   level = 10,
   model = {"models/codmw2/t_codm.mdl"},
   description = [[You are a Lieutenant for the United States Army. Your job is to muster a squad of teammates to patrol, raid, defend, ect. You take orders from the Colonel.]],
   weapons = {"cw_g4p_masada_acr",  "cw_g4p_glock17"},
   command = "uslieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US8 = DarkRP.createJob("US Colonel", {
	level = 75,
   color = Color(0, 128, 255, 255),
   model = {"models/codmw2/codmw2he.mdl"},
   description = [[You are a Colonel for the United States Army. Your take orders from the General of the Army and command your troops the way you want to, to get the mission done.]],
   weapons = {"cw_g4p_m16a2", "cw_g4p_glock17"},
   command = "uscolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
})

TEAM_US9 = DarkRP.createJob("US General of the Army", {
	level = 100,
   color = Color(0, 128, 255, 255),
   model = {"models/player/pmc_2/pmc__01.mdl"},
   description = [[You are the U.S General of the Army. You declare wars, accept peace treaties, alliances, ect. You order the Colonel on what to do and the Colonel will see it done.]],
   weapons = {},
   command = "usgota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United States",
   PlayerDeath = function(ply, weapon, killer)
		ply:teamBan()
		ply:changeTeam(GAMEMODE.DefaultTeam, true)
		if killer:IsPlayer() then
			DarkRP.notifyAll(0, 4, "The U.S General of the Army has been killed!")
		else
			DarkRP.notifyAll(0, 4, "The U.S General of the Army has died!")
		end
	end
})																																							

//TEAM_US10 = DarkRP.createJob("US Speacial Forces", {
  // color = Color(0, 128, 255, 255),
   //model = {"models/codmw2/codmw2m.mdl"},
   //description = [[You are  a one manned special forces "team". You take orders directly from the General of the Army.]],
  // weapons = {"cw_kriss_5_vector", "cw_g4p_g2contender", "cw_g4p_glock17"},
  // command = "usspecialforces",
   //max = 2,
   //salary = 250,
   //admin = 0,
   //vote = false,
   //hasLicense = false,
   //candemote = true,
   //category = "United States",
//})

/*// RUSSIA //

TEAM_RU1 = DarkRP.createJob("RU Infantry", {
	level = 5,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_a.mdl"},
   description = [[You are an infantry unit for the Russian Army .Follow your superior's orders and lead Russia to victory!]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "ruinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Russia",
})

TEAM_RU2 = DarkRP.createJob("RU Recon Unit", {
	level = 1,
   color = Color(228, 0, 0, 255),
   model = {"models/player/pmc_5/pmc__03.mdl"},
   description = [[You are a recon unit for the Russian Army. Your job is to gather intel on enemy units.]],
   weapons = {"util_binoculars", "m9k_hk45"},
   command = "rurecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU3 = DarkRP.createJob("RU Heavy Infantry", {
	level = 20,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/riot/riot_ru.mdl"},
   description = [[You are a heavy infantry unit for the Russian Army. You are up close and personal and would be the first to enter a base while raiding.]],
   weapons = {"m9k_remington870", "m9k_hk45", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "ruheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU4 = DarkRP.createJob("RU Sniper", {
	level = 30,
   color = Color(228, 0, 0, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for the Russia Army. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"m9k_dragunov", "m9k_hk45"},
   command = "rusniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU5 = DarkRP.createJob("RU Light Machine Gunner", {
	level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/riot/riot_ru.mdl"},
   description = [[You are a light machine gunner for the Russian Army. Your job is to defend your base. YOU ARE NOT TO JOIN RAIDS. YOU ARE A DEFENSIVE UNIT, NOT AN OFFENSIVE UNIT!]],
   weapons = {"m9k_pkm", "m9k_hk45"},
   command = "rulightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU6 = DarkRP.createJob("RU Medic", {
	level = 15,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_d.mdl"},
   description = [[You are a medic for the Russian Army. You're job is to heal your team and keep them alive!]],
   weapons = {"weapon_medkit", "m9k_an94", "m9k_hk45"},
   command = "rumedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU7 = DarkRP.createJob("RU Lieutenant", {
	level = 50,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_c.mdl"},
   description = [[You are a Lieutenant for the Russian Army. Your job is to muster a squad of teammates to patrol, raid, defend, ect. You take orders from the Colonel.]],
   weapons = {"m9k_amd65", "m9k_hk45"},
   command = "rulieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU8 = DarkRP.createJob("RU Colonel", {
	level = 75,
   color = Color(228, 0, 0, 255),
   model = {"models/mw2guy/rus/soldier_e.mdl"},
   description = [[You are a Colonel for the Russian Army. Your take orders from the General of the Army and command your troops the way you want to, to get the mission done.]],
   weapons = {"m9k_ak74", "m9k_hk45"},
   command = "rucolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
})

TEAM_RU9 = DarkRP.createJob("RU General of the Army", {
	level = 100,
   color = Color(228, 0, 0, 255),
   model = {"models/player/pmc_5/pmc__01.mdl"},
   description = [[You are the Russian General of the Army. You declare wars, accept peace treaties, alliances, ect. You order the Colonel on what to do and the Colonel will see it done.]],
   weapons = {},
   command = "rugota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Russia",
   PlayerDeath = function(ply, weapon, killer)
		ply:teamBan()
		ply:changeTeam(GAMEMODE.DefaultTeam, true)
		if killer:IsPlayer() then
			DarkRP.notifyAll(0, 4, "The Russian General of the Army has been killed!")
		else
			DarkRP.notifyAll(0, 4, "The Russian General of the Army has died!")
		end
	end
})
*/
// GERMANY //


// FUTURE MILITARY POWER //
// Master Chief = models/player/Rottweiler/mc.mdl
TEAM_NWO1 = DarkRP.createJob("NWO Infantry", {
	level = 50,
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[You are an infantry unit for the NWO Army .Follow your superior's orders and lead Russia to victory!]],
   weapons = {"cw_mn23", "cw_g4p_glock17"},
   command = "nwoinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "New World Order",
})

TEAM_NWO2 = DarkRP.createJob("NWO Recon Unit", {
	level = 100,
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[You are a recon unit for the NWO Army. Your job is to gather intel on enemy units. YOU ARE NOT ALLOWED TO OWN WEAPONS!]],
   weapons = {"util_binoculars", "weapon_stealthcamo"},
   command = "nworecon",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   customCheck = function(ply)
        return ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_NWO3 = DarkRP.createJob("NWO Heavy Infantry", {
	level = 70,
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[You are a heavy infantry unit for the NWO Army. You are up close and personal and would be the first to enter a base while raiding.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "nwoheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO4 = DarkRP.createJob("NWO Sniper", {
	level = 60,
   color = Color(0, 20, 84, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for the NWO Army. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"cw_g4p_awm", "cw_g4p_glock17"},
   command = "nwosniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO5 = DarkRP.createJob("NWO Light Machine Gunner", {
	level = 80,
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[You are a light machine gunner for the NWO Army. Your job is to defend your base. YOU ARE NOT TO JOIN RAIDS. YOU ARE A DEFENSIVE UNIT, NOT AN OFFENSIVE UNIT!]],
   weapons = {"cw_240b", "cw_g4p_glock17"},
   command = "nwolightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO6 = DarkRP.createJob("NWO Medic", {
	level = 55,
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[You are a medic for the NWO Army. You're job is to heal your team and keep them alive!]],
   weapons = {"weapon_medkit", "cw_mp5", "cw_g4p_glock17"},
   command = "nwomedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO7 = DarkRP.createJob("NWO Lieutenant", {
	level = 65,
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4pm.mdl"},
   description = [[You are a Lieutenant for the NWO Army. Your job is to muster a squad of teammates to patrol, raid, defend, ect. You take orders from the Colonel.]],
   weapons = {"cw_g4p_xm8", "cw_g4p_glock17"},
   command = "nwolieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO8 = DarkRP.createJob("NWO Colonel", {
	level = 90,
   color = Color(0, 20, 84, 255),
   model = {"models/odstvariants/odsthalo4/odsthalo4camopm.mdl"},
   description = [[You are a Colonel for the NWO Army. Your take orders from the General of the Army and command your troops the way you want to, to get the mission done.]],
   weapons = {"cw_g4p_magpul_masada", "cw_g4p_glock17"},
   command = "nwocolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
})

TEAM_NWO9 = DarkRP.createJob("NWO General of the Army", {
	level = 100,
   color = Color(0, 20, 84, 255),
   model = {"models/player/Rottweiler/mc.mdl"},
   description = [[You are the NWO General of the Army. You declare wars, accept peace treaties, alliances, ect. You order the Colonel on what to do and the Colonel will see it done.]],
   weapons = {},
   command = "nwogota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "New World Order",
   PlayerDeath = function(ply, weapon, killer)
		ply:teamBan()
		ply:changeTeam(GAMEMODE.DefaultTeam, true)
		if killer:IsPlayer() then
			DarkRP.notifyAll(0, 4, "The NWO General of the Army has been killed!")
		else
			DarkRP.notifyAll(0, 4, "The NWO General of the Army has died!")
		end
	end
})





TEAM_DE1 = DarkRP.createJob("DE Infantry", {
	level = 1,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__12.mdl"},
   description = [[You are an infantry unit for the German Army .Follow your superior's orders and lead Germany to victory!]],
   weapons = {"cw_g4p_g36c", "cw_g4p_usp40"},
   command = "deinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Germany",
})

TEAM_DE2 = DarkRP.createJob("DE Recon Unit", {
	level = 1,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__03.mdl"},
   description = [[You are a recon unit for the German Army. Your job is to gather intel on enemy units.]],
   weapons = {"util_binoculars", "cw_g4p_usp40"},
   command = "derecon",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE3 = DarkRP.createJob("DE Heavy Infantry", {
	level = 20,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__14.mdl"},
   description = [[You are a heavy infantry unit for the German Army. You are up close and personal and would be the first to enter a base while raiding.]],
   weapons = {"cw_xm1014", "cw_g4p_usp40", "weapon_doorbuster", "lockpick", "keypad_cracker"},
   command = "deheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE4 = DarkRP.createJob("DE Sniper", {
	level = 30,
   color = Color(32, 32, 32, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for the German Army. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"cw_g4p_m98b", "cw_g4p_usp40"},
   command = "desniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE5 = DarkRP.createJob("DE Light Machine Gunner", {
	level = 50,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__13.mdl"},
   description = [[You are a light machine gunner for the German Army. Your job is to defend your base. YOU ARE NOT TO JOIN RAIDS. YOU ARE A DEFENSIVE UNIT, NOT AN OFFENSIVE UNIT!]],
   weapons = {"cw_240b", "cw_g4p_usp40"},
   command = "delightmachinegunner",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE6 = DarkRP.createJob("DE Medic", {
	level = 15,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__02.mdl"},
   description = [[You are a medic for the German Army. You're job is to heal your team and keep them alive!]],
   weapons = {"weapon_medkit", "cw_mp5", "cw_g4p_usp40"},
   command = "demedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE7 = DarkRP.createJob("DE Lieutenant", {
	level = 50,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__07.mdl"},
   description = [[You are a Lieutenant for the German Army. Your job is to muster a squad of teammates to patrol, raid, defend, ect. You take orders from the Colonel.]],
   weapons = {"cw_g4p_xm8", "cw_g4p_usp40"},
   command = "delieutenant",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE8 = DarkRP.createJob("DE Colonel", {
	level = 75,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__04.mdl"},
   description = [[You are a Colonel for the German Army. Your take orders from the General of the Army and command your troops the way you want to, to get the mission done.]],
   weapons = {"cw_g4p_fn_fal", "cw_g4p_usp40"},
   command = "decolonel",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
})

TEAM_DE9 = DarkRP.createJob("DE General of the Army", {
	level = 100,
   color = Color(32, 32, 32, 255),
   model = {"models/player/pmc_4/pmc__01.mdl"},
   description = [[You are the German General of the Army. You declare wars, accept peace treaties, alliances, ect. You order the Colonel on what to do and the Colonel will see it done.]],
   weapons = {},
   command = "degota",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "Germany",
   PlayerDeath = function(ply, weapon, killer)
		ply:teamBan()
		ply:changeTeam(GAMEMODE.DefaultTeam, true)
		if killer:IsPlayer() then
			DarkRP.notifyAll(0, 4, "The German General of the Army has been killed!")
		else
			DarkRP.notifyAll(0, 4, "The German General of the Army has died!")
		end
	end
})

				
// C.E.L.L Military Company (Mercenaries) //

TEAM_CELL1 = DarkRP.createJob("C.E.L.L Infantry", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault1player.mdl"},
   description = [[You are an infantry unit for the PMCs. Follow your orders and get paid.]],
   weapons = {"cw_g4p_glock17", "cw_g4p_magpul_masada"},
   command = "cellinfantry",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
    customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL2 = DarkRP.createJob("C.E.L.L Heavy Infantry", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault3player.mdl"},
   description = [[You are a heavy infantry unit for C.E.L.L Military Company. You are up close and personal and would be the first to enter a base while raiding.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick", "keypad_cracker"},
   command = "cellheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
   customCheck = function(ply)
        return ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL3 = DarkRP.createJob("C.E.L.L Recon Unit", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault4player.mdl"},
   description = [[You are a recon unit for the C.E.L.L Military Company. Your job is to gather intel on enemy units]],
   weapons = {"cw_g4p_glock17", "util_binoculars"},
   command = "cellreconunit",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
   customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL4 = DarkRP.createJob("C.E.L.L Medic", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault1player.mdl"},
   description = [[You are a recon unit for the C.E.L.L Military Company. Your job is to gather intel on enemy units]],
   weapons = {"weapon_medkit", "m9k_vector", "cw_g4p_glock17"}, 
   command = "cellmedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
    customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL5 = DarkRP.createJob("C.E.L.L Commander", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/mgs4_bigboss.mdl"},
   description = [[You are the Commander for C.E.L.L Military Company. Command your troops and accept or deny requests of hire.]],
   weapons = {},
   command = "cellcommander",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
    customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL6 = DarkRP.createJob("C.E.L.L Juggernaut", {
   color = Color(0, 204, 204, 255),
   model = {"models/mw2guy/riot/juggernaut.mdl"},
   description = [[You are a juggernaut for C.E.L.L Military Company. Take orders from your superior, and remember, no russian.]],
   weapons = {"cw_240b", "cw_g4p_ump45", "cw_deagle"},
   command = "celljuggernaut",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
   PlayerSpawn =  function(ply) ply:SetArmor(200) ply:SetAmmo(600 , "ar2") end,
    customCheck = function(ply)
        return ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL7 = DarkRP.createJob("C.E.L.L Officer", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault1player.mdl"},
   description = [[You are an officer for C.E.L.L Military Company. Command your troops out in the field and make sure you don't disappoint your customer.]],
   weapons = {"cw_g4p_magpul_masada", "cw_g4p_glock17"},
   command = "cellofficer",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
    customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL8 = DarkRP.createJob("C.E.L.L Special Forces", {
   color = Color(0, 204, 204, 255),
   model = {"models/player/cellassault1player.mdl"},
   description = [[You are special forces for C.E.L.L Military Company. You do not work with other parts of the company. You either work solo or with the other special forces in the company. You take orders directly from the Commander.]],
   weapons = {"cw_mn23", "cw_g4p_awm", "cw_g4p_glock17"},
   command = "cellspecialforces",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
   customCheck = function(ply)
        return ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_CELL9 = DarkRP.createJob("C.E.L.L Sniper", {
   color = Color(0, 204, 204, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for C.E.L.L Military Company. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"cw_g4p_awm", "cw_g4p_glock17"},
   command = "cellsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "C.E.L.L Military Company (Mercenaries)",
    customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

// TERRORISTS //

TEAM_T1 = DarkRP.createJob("Terrorist", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_grunt.mdl"},
   description = [[You are  a standard terrorist. Take orders from your leader. REMEMBER YOU CAN ONLY DO A TERRORIST ATTACK EVERY 30 MINUTES!]],
   weapons = {},
   command = "terrorist",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 2,
   category = "Terrorists",
   customCheck = function(ply)
        return ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})

TEAM_T2 = DarkRP.createJob("Terrorist Leader", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_rpg.mdl"},
   description = [[You are the leader of the terrorists. Tell your other terrorists your plans for maximum chaos! REMEMBER YOU CAN ONLY DO A TERRORIST ATTACK EVERY 30 MINUTES!]],
   weapons = {},
   command = "terroristleader",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 1,
   category = "Terrorists",
   customCheck = function(ply)
        return ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,

})

TEAM_T3 = DarkRP.createJob("Suicide Bomber", {
   color = Color(102, 102, 0, 255),
   model = {"models/player/kuma/taliban_bomber.mdl"},
   description = [[You are a suicide bomber! Blow yourself up to cause chaos! REMEMBER YOU CAN ONLY DO A TERRORIST ATTACK EVERY 15 MINUTES!]],
   weapons = {"m9k_suicide_bomb"},
   command = "suicidebomber",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   sortOrder = 3,
   category = "Terrorists",
   customCheck = function(ply)
        return ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,

})

// UNITED NATIONS //

TEAM_UN1 = DarkRP.createJob("UN Infantry", {
	level = 5,
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_assault.mdl"},
   description = [[You are infantry for the United Nations. Work with the factions to bring peace!]],
   weapons = {"cw_ar15", "cw_g4p_glock17"},
   command = "uninfantry",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
})
/*
TEAM_UN2 = DarkRP.createJob("UN Defense Unit", {
	level = 50,
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[You are a defense unit for the United Nations. Protect the base or whatever your superiors tells you to.]],
   weapons = {"m9k_m249lmg", "bb_glock_alt"},
   command = "undefenseunit",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})
*/
TEAM_UN3 = DarkRP.createJob("UN Medic", {
	level = 15,
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_medic.mdl"},
   description = [[You are a medic for the United Nations. Keep your team alive!]],
   weapons = {"cw_g4p_ump45", "cw_g4p_glock17", "med_kit"},
   command = "unmedic",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
})

TEAM_UN4 = DarkRP.createJob("UN Heavy Infantry", {
	level = 20,
   color = Color(0, 0, 255, 255),
   model = {"models/player/mnu_soldier.mdl"},
   description = [[You are heavy infantry for the United Nations. Bust down doors and provide support to the team.]],
   weapons = {"cw_xm1014", "cw_g4p_glock17", "lockpick"},
   command = "unheavyinfantry",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})
/*
TEAM_UN5 = DarkRP.createJob("UN Sniper", {
	level = 30,
   color = Color(0, 0, 255, 255),
   model = {"models/jessev92/player/military/cod4_sniper.mdl"},
   description = [[You are a sniper for the United Nations. Follow you officer's orders and use your sniping skills to take down foes! Work with the recon unit for maximum proficiency!]],
   weapons = {"m9k_intervention", "bb_glock_alt"},
   command = "unsniper",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
   customCheck = function(ply)
        return ply:IsUserGroup("bronze") or ply:IsUserGroup("silver") or ply:IsUserGroup("gold") or ply:IsUserGroup("titanium") or ply:IsAdmin()
    end,
})
*/
TEAM_UN6 = DarkRP.createJob("UN Lieutenant", {
   color = Color(0, 0, 255, 255),
   level = 50,
   model = {"models/player/mnu_soldier.mdl"},
   description = [[You are a Lieutenant for the United Nations. Command your troops while out in the field and organize your defense tactics. You take orders from the Ambassador.]],
   weapons = {"cw_g3a3", "cw_g4p_glock17"},
   command = "unlieutenant",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
})

TEAM_UN7 = DarkRP.createJob("UN Ambassador", {
   color = Color(0, 0, 255, 255),
   level = 3,
   model = {"models/player/pmc_1/pmc__01.mdl"},
   description = [[You are the Ambassador for the United Nations. Decide which factions you will support and which factions to oppose to bring peace!]],
   weapons = {},
   command = "unambassador",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = true,
   category = "United Nations",
})

--[[// U.S BREACHER
// models/codmw2/codmw2.mdl

// U.S COLONEL
// models/codmw2/codmw2he.mdl

// U.S | LIEUTENANT W/ MORE GEAR
// models/codmw2/codmw2hexe.mdl

// GHOST
// models/codmw2/codmw2m.mdl

// U.S LIEUTENANT
// models/codmw2/t_codm.mdl]]

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1


/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("United States", TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)
--AddDoorGroup("Russia", TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)
AddDoorGroup("New World Order", TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)
AddDoorGroup("Germany", TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)
AddDoorGroup("United Nations", TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)


/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
DarkRP.createAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))
Its possible to have multiple managers. In that case you have to put all the managers in '{}' (see Police agenda)

The default agendas, can also be used as examples:
*/
DarkRP.createAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
DarkRP.createAgenda("Police agenda", {TEAM_MAYOR, TEAM_CHIEF}, {TEAM_POLICE})


/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
DarkRP.createGroupChat(List of team variables separated by comma)

or

DarkRP.createGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_US1, TEAM_US2, TEAM_US3, TEAM_US4, TEAM_US5, TEAM_US6, TEAM_US7, TEAM_US8, TEAM_US9)

--DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
--DarkRP.createGroupChat(TEAM_RU1, TEAM_RU2, TEAM_RU3, TEAM_RU4, TEAM_RU5, TEAM_RU6, TEAM_RU7, TEAM_RU8, TEAM_RU9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_NWO1, TEAM_NWO2, TEAM_NWO3, TEAM_NWO4, TEAM_NWO5, TEAM_NWO6, TEAM_NWO7, TEAM_NWO8, TEAM_NWO9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_DE1, TEAM_DE2, TEAM_DE3, TEAM_DE4, TEAM_DE5, TEAM_DE6, TEAM_DE7, TEAM_DE8, TEAM_DE9)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_CELL1, TEAM_CELL2, TEAM_CELL3, TEAM_CELL4, TEAM_CELL5, TEAM_CELL6, TEAM_CELL7, TEAM_CELL8)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_UN1, TEAM_UN2, TEAM_UN3, TEAM_UN4, TEAM_UN5, TEAM_UN6, TEAM_UN7)

DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)
DarkRP.createGroupChat(TEAM_T1, TEAM_T2, TEAM_T3)
/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Default categories
---------------------------------------------------------------------------*/

DarkRP.createCategory{
	name = "Administration",
	categorises = "jobs",
	startExpanded = false,
	color = Color(255, 0, 0, 255),
	canSee = fp{fn.Id, false},
	sortOrder = 1,
}

DarkRP.createCategory{
	name = "United States",
	categorises = "jobs",
	startExpanded = false,
	color = Color(0, 150, 255, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 3,
}

DarkRP.createCategory{
	name = "New World Order",
	categorises = "jobs",
	startExpanded = false,
	color = Color(0, 20, 84, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 4,
}

/*
DarkRP.createCategory{
	name = "Russia",
	categorises = "jobs",
	startExpanded = false,
	color = Color(255, 0, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 5,
}
*/

DarkRP.createCategory{
	name = "Germany",
	categorises = "jobs",
	startExpanded = false,
	color = Color(32, 32, 32, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 6,
}

DarkRP.createCategory{
	name = "United Nations",
	categorises = "jobs",
	startExpanded = false,
	color = Color(0, 0, 255, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 7,
}

DarkRP.createCategory{
	name = "C.E.L.L Military Company (Mercenaries)",
	categorises = "jobs",
	startExpanded = false,
	color = Color(0, 204, 204, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 8,
}

DarkRP.createCategory{
	name = "Terrorists",
	categorises = "jobs",
	startExpanded = false,
	color = Color(102, 102, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 9,
}

DarkRP.createCategory{
	name = "Other",
	categorises = "jobs",
	startExpanded = false,
	color = Color(0, 107, 0, 255),
	canSee = fp{fn.Id, true},
	sortOrder = 255,
}
